---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: "versioncheck.yml"
  when: submodules_versioncheck | bool

# - name: Register variables
#   ansible.builtin.import_tasks:
#     file: variables.yml

- name: Ensure i3 packages are installed [Debian]
  ansible.builtin.include_tasks:
    file: "setup-Debian.yml"
  when: ansible_os_family == 'Debian'

- name: Create sway configuration and features
  ansible.builtin.import_tasks:
    file: "config.yml"

- name: Create waybar config
  ansible.builtin.include_tasks:
    file: "waybar.yml"
  loop: "{{ sway__user_list | flatten(1) }}"
  loop_control:
    loop_var: swayusr
    label: "{{ swayusr.home }}/.config/waybar/"
  when: sway__waybar | bool

# -  name: Ensure i3 packages are installed [Archlinux}
#    ansible.builtin.include_tasks:
#      file: setup-Archlinux.yml
#    when: ansible_os_family == 'Archlinux'
#
# -  name: Ensure i3 packages are installed [RHEL].
#    ansible.builtin.include_tasks:
#      file: setup-RedHat.yml
#    when: ansible_os_family == 'Fedora' or ansible_os_family == 'RedHat'

# - name: Create i3 config file
#   ansible.builtin.include_tasks:
#     file: config.yml
#   loop: "{{ i3wm_user_list | flatten(1) }}"
#   loop_control:
#     loop_var: i3wm_usr
