---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: "versioncheck.yml"
  when: submodules_versioncheck | bool

# - name: Register variables
#   ansible.builtin.import_tasks:
#     file: variables.yml

- name: Ensure i3 packages are installed [Debian]
  ansible.builtin.include_tasks:
    file: "setup-Debian.yml"
  when: ansible_os_family == 'Debian'

- name: Install wlsunset
  ansible.builtin.import_tasks:
    file: "wlsunset.yml"
  when: sway__wlsunset | bool

- name: Create sway configuration and features
  ansible.builtin.import_tasks:
    file: "config.yml"

- name: Create waybar config
  ansible.builtin.include_tasks:
    file: "waybar.yml"
  loop: "{{ sway__user_list | flatten(1) }}"
  loop_control:
    loop_var: swayusr
    label: "{{ swayusr.home }}/.config/waybar/"
  when: sway__waybar | bool
