---
- name: Register OS-specific Variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"
  when: ansible_distribution != "Fedora"

- name: Register Fedora-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Fedora"

- name: Define i3_packages
  ansible.builtin.set_fact:
    i3_packages: "{{ __i3_packages | list }}"
  when: i3_packages is not defined

- name: Define i3_packages_extra
  ansible.builtin.set_fact:
    i3_packages: "{{ i3_packages | list + i3_packages_extra | list }}"
  when: i3_packages_extra is defined

- name: Define i3_packages
  ansible.builtin.set_fact:
    i3_workspaces: "{{ __i3_workspaces | list }}"
  when: i3_workspaces is not defined

- name: Define i3_keybindings
  ansible.builtin.set_fact:
    i3_keybindings: "{{ __i3_keybindings | list }}"
  when:
    - i3_keybindings is not defined
    - __i3_keybindings is defined

- name: Define additional i3 keybindings
  ansible.builtin.set_fact:
    i3_keybindings: "{{ i3_keybindings_extra | list + i3_keybindings | list }}"
  when:
    - i3_keybindings_extra is defined
    - i3_keybindings is defined

- name: Finalize i3 keybindings definition
  ansible.builtin.set_fact:
    i3_keybindings: "{{ i3_keybindings_extra | list }}"
  when:
    - i3_keybindings_extra is defined
    - i3_keybindings is not defined
