# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "debian" do |web|
      web.vm.box = "debian/stretch64"

      web.vm.provider "virtualbox" do |vb|
         vb.memory = "512"
      end
  end

  config.vm.define "xenial" do |web|
      web.vm.box = "ubuntu/xenial64"

      web.vm.provider "virtualbox" do |vb|
         vb.memory = "512"
      end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.groups = {
        "all" => ["debian", "xenial"]
    }
    ansible.raw_arguments = ["-u vagrant"]
  end

end
